# Generated by Django 3.2.4 on 2021-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
