# Generated by Django 3.2.4 on 2021-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210610_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoModel',
        ),
        migrations.AddField(
            model_name='photo',
            name='model',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
